# Site
name: 'GoodShifter'
description: 'GoodShifter - The app guiding consumers towards better habits, with small but impactful steps.'

# logo: 'assets/images/GoodShifter - Logo v2 Light Shadow - Close - Transparent.png'
# logo: 'assets/images/GoodShifter Logo - V1.0.png'
logo: 'assets/images/uploads/goodshifter-logo-v1.0-banner-no-margin.png'
favicon: 'assets/images/favicon.png'

url: "https://goodshifter.com"
baseurl: ""

avatar: 'assets/images/sal.jpg'
disqus: 'goodshifter'
email: 'wowthemesnet@gmail.com'

permalink: /:categories/:title/

future: true
draft: false

include:
  - _pages
  - .htaccess
  - error_404.md

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
  - _archives
  - _examples

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
 
# Defaults
defaults:
  # all posts
  - scope:
      path: "*/_posts"
    values:
      layout: post
      comments: true
      
  # all pages
  - scope:
      path: "*/_pages"
    values:
      layout: page
      comments: false

  # Français
  - scope:
      path: "fr"
    values:
      lang: "fr"

  #English
  - scope:
      path: "en"
    values:
      lang: "en"


# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20
